apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: hazlecasttest
build:
  artifacts:
    - image: micronaut-hazelcast-k8-demo
      context: .
      jib: {}
deploy:
  kubectl:
    manifests:
    - k8s/deployment-default.yml

portForward:
  - resourceType: service
    resourceName: cache-service
    namespace: default
    port: 8080
    localPort: 8080 # *Optional*
