apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-service
  labels:
    app: cache-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cache-service
  template:
    metadata:
      labels:
        app: cache-service
    spec:
      serviceAccountName: default
      containers:
        - name: cache-service
          image: micronaut-hazelcast-k8-demo:latest
          ports:
            - name: http
              containerPort: 8080
            - name: multicast
              containerPort: 5701
          env:
            - name: MICRONAUT_ENVIRONMENTS
              value: localk8
---
apiVersion: v1
kind: Service
metadata:
  name: cache-service
  namespace: default
  labels:
    app: cache-service
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: cache-service
#  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-service
  namespace: default
spec:
  selector:
    app: cache-service
  ports:
    - name: hazelcast
      port: 5701
      protocol: TCP
#  type: NodePort